version: "3"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./alumni:/var/www/html/
        links:
            - db
        networks:
            - public
            - internal
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: alumni
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./db_alumni:/var/lib/mysql/
        networks:
            - internal
    rabbit:
        image: rabbitmq:3.7.7-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        networks:
            - internal
    node:
        image: node:8.11.4-alpine
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        ports: 
            - "3000:3000"
        volumes:
            - ./node:/home/node/app/
        command: "npm start"
        links:
            - rabbit
        depends_on:
            - "rabbit"
        networks:
            - public
            - internal

volumes:
    db_alumni:

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true