version: "3"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./alumni:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: alumni
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - ./db_alumni:/var/lib/mysql/
        networks:
            - default
    rabbit:
        image: rabbitmq:3.7.7-management-alpine
        ports:
            - "15672:15672"
            - "5672:5672"
            - "8080:8080"
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
    node:
        image: node:8.11.4-alpine
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        ports: 
            - "3000:3000"
        volumes:
            - ./node:/home/node/app/
        command: "npm start"
        links:
            - rabbit
        depends_on:
            - "rabbit"

volumes:
    db_alumni: