#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path:       /
    controller: App\Controller\DefaultController::homepage

admin:
    path:       /admin
    controller: App\Controller\AdminController::admin

signup:
    path:       /signup/{invitationId}
    controller: App\Controller\SignupController::signup

login:
    path:       /login
    controller: App\Controller\DefaultController::login
    
logout:
    path:       /logout

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
    
group_list:
    path:       /admin/groups
    controller: App\Controller\AdminController::listGroups

profile:
    path:       /profile
    controller: App\Controller\ProfileController::profile

profile_edit:
    path:       /profile/edit{user}
    controller: App\Controller\ProfileController::profileEdit

user_list:
    path:       /users
    controller: App\Controller\DefaultController::listUsers

post:
    path:       /post
    controller: App\Controller\PostController::createPost


