#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path:     /
  controller: App\Controller\DefaultController::homepage
  
login:
    path:       /login
    controller: App\Controller\DefaultController::login

logout:
  path: /logout
