#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path:       /
    controller: App\Controller\DefaultController::homepage

admin:
    path:       /admin
    controller: App\Controller\AdminController::admin

signup:
    path:       /signup
    controller: App\Controller\SignupController::signup

login:
    path:       /login
    controller: App\Controller\DefaultController::login
    
logout:
    path: /logout

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
    
group_list:
    path:       /groups
    controller: App\Controller\AdminController::listGroups


  



