#index:
#    path: /
#    controller: App\Controller\DefaultController::index

group_list:
  path:       /groups
  controller: App\Controller\AdminController::listGroups

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
