#index:
#    path: /
#    controller: App\Controller\DefaultController::index


admin:
    path:       /admin
    controller: App\Controller\AdminController::admin

signup:
    path:       /signup/{invitation}
    controller: App\Controller\SignupController::signup

group_list:
    path:       /admin/groups
    controller: App\Controller\AdminController::listGroups

homepage:
    path:       /
    controller: App\Controller\DefaultController::homepage
  
login:
    path:       /login
    controller: App\Controller\DefaultController::login
    
logout:
    path:       /logout

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
    
profile:
    path:       /profile
    controller: App\Controller\ProfileController::profile

profile_edit:
    path:       /profile/edit
    controller: App\Controller\ProfileController::profileEdit

cv_edit:
    path:       /profile/cv
    controller: App\Controller\ProfileController::cvEdit

user_list:
    path:       /users
    controller: App\Controller\SearchController::listUsers

post:
    path:       /post
    controller: App\Controller\PostController::createPost

posts:
    path:       /posts/{creationDate}
    controller: App\Controller\PostController::getPosts

post_list:
    path:       /post/list
    controller: App\Controller\PostListController::postList

delete_post:
    path:       /post/delete/{id}
    controller: App\Controller\PostController::deletePost

delete_comment:
    path:       /comment/delete/{id}
    controller: App\Controller\CommentController::delete

comment:
    path:       /comment/{post}
    controller: App\Controller\CommentController::comment

flag_post:
    path:       /post/{post}/flag
    controller: App\Controller\PostController::flagPost

new_conversation:
    path:       /conversation/new/{user}
    controller: App\Controller\ConversationController::newConversation

new_message:
    path:       /newMessage
    controller: App\Controller\MessageController::receiveMessage

get_user:
    path:       /user
    controller: App\Controller\UserController::getCurrentUser
    
post_user_edit:
    path:       /post/edit/{id}
    controller: App\Controller\PostController::editUserPost

comment_user_edit:
    path:       /comment/edit/{id}
    controller: App\Controller\CommentController::editUserComment

flags:
    path:       /admin/flags
    controller: App\Controller\AdminController::listFlags
    
post_edit:
    path:       /admin/flags/post/edit/{post}
    controller: App\Controller\AdminController::editPost

comment_edit:
    path:       /admin/flags/comment/edit/{comment}
    controller: App\Controller\AdminController::editComment

profile_search:
    path:       /users/search{user}
    controller: App\Controller\SearchController::showUser 


get_user_conversations:
    path:       /user/conversations
    controller: App\Controller\UserController::getCurrentUserConversations

unpublished_posts:
    path:       /profile/unpublished
    controller: App\Controller\PostListController::showUnpublishedPosts

#this route absolutely needs to be at the bottom!!!!!!!!!#
download_document:
    path:       /profile/{document}
    controller: App\Controller\ProfileController::downloadDocument



