#index:
#    path: /
#    controller: App\Controller\DefaultController::index


admin:
    path:       /admin
    controller: App\Controller\AdminController::admin

signup:
    path:       /signup/{invitation}
    controller: App\Controller\SignupController::signup

group_list:
    path:       /admin/groups
    controller: App\Controller\AdminController::listGroups

homepage:
    path:       /
    controller: App\Controller\DefaultController::homepage
  
login:
    path:       /login
    controller: App\Controller\DefaultController::login
    
logout:
    path:       /logout

invitation:
    path:       /admin/invitation
    controller: App\Controller\AdminController::invitation
    
profile:
    path:       /profile
    controller: App\Controller\ProfileController::profile

profile_edit:
    path:       /profile/edit
    controller: App\Controller\ProfileController::profileEdit

picture_edit:
    path:       /profile/picture
    controller: App\Controller\PictureController::pictureEdit

cv_edit:
    path:       /profile/cv
    controller: App\Controller\CvController::cvEdit

user_list:
    path:       /users
    controller: App\Controller\SearchController::listUsers

post:
    path:       /post
    controller: App\Controller\PostController::createPost

posts:
    path:       /posts/{creationDate}
    controller: App\Controller\PostController::getPosts
post_list:

    path:       /post/list
    controller: App\Controller\PostListController::postList

comment:
    path:       /comment/{post}
    controller: App\Controller\CommentController::comment

flag_post:
    path:       /post/{post}/flag
    controller: App\Controller\PostController::flagPost



